version: "3.9"

services:
  fastapi_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/home/app
    networks:
      - postgres-network
    depends_on:
      - db_postgres
    container_name: fastapi_app
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000 --reload

  db_postgres:
    image: postgres:13.3-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
    external: true
